pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_app_stage'

            }
            
        }
        stage('deploy in prod'){
            steps{
                timeout(time:5,unit:'DAYS'){
                    input message:'Approve production deployment?'
                }
                build job:'prod1'
            }
        }
    }
}